name: Kotlin build
author: Cameron
description: ⤵️ Create pull request
branding:
  icon: 'git-pull-request'
  color: 'black'
inputs:
  source_branch:
    description: Branch name to pull from, default is triggered branch
    required: false
  destination_branch:
    description: Branch name to sync to in this repo, default is master
    required: false
    default: master
  pr_title:
    description: Pull request title
    required: false
  pr_body:
    description: Pull request body
    required: false
  pr_template:
    description: Pull request template
    required: false
  pr_reviewer:
    description: Pull request reviewers, comma-separated list (no spaces)
    required: false
  pr_assignee:
    description: Pull request assignees, comma-separated list (no spaces)
    required: false
  pr_label:
    description: Pull request labels, comma-separated list (no spaces)
    required: false
  github_token:
    description: GitHub token secret
    required: true  
    
on:
  push:
    branches:
    - develop
  pull_request:
    branches:
    - develop

jobs: 
  build:
    runs-on: ubuntu-latest

    steps: 
      - uses : actions/checkout@v1


      - name: set up JDK
        uses: actions/setup-java@v1
        with: 
          java-version: 15.0.2


      - name: Emplacement of racine file
        run: ls -ali
      
      
      - name: Emplacement of racine file
        run: dir


      - name: Make gradlew executable
        run: chmod +x ./epicture_project/gradlew


      - name: Build with Gradle
        run: ./epicture_project/gradlew build

      - name: Build Debug APK
        run: ./gradlew assembleDebug


      - name: Releasing apk
        uses: Celesxx/Epicture@main
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
          APP_FOLDER: ./
          RELEASE_TITLE: New Build