on:
  push:
    branches:
    - develop
  pull_request:
    branches:
    - develop

jobs:
  pull-request:
    runs-on: ubuntu-latest
    - uses: actions/checkout@v2

    steps:
    - name: pull-request
      uses: Celesxx/create-pull-request@v3
      with:
          base: main