on:
  push:
    branches:
    - develop
  pull_request:
    branches:
    - develop
  
jobs:
  Build_release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Releasing using Hub
            uses: ShaunLWM/action-release-debugapk@master
            env:
            GITHUB_TOKEN: ${{ secrets.TOKEN }}
            APP_FOLDER: app
            RELEASE_TITLE: New Build