name: Kotlin build

on:
  push:
    branches:
    - develop
  pull_request:
    branches:
    - develop

jobs: 
  build:
    runs-on: ubuntu-latest

    steps: 
      - uses : actions/checkout@v1


      - name: set up JDK
        uses: actions/setup-java@v1
        with: 
          java-version: 15.0.2
      # - name: Run tests
      #   run: ./gradlew test

      - name: Build project
        run: ./gradlew assemble