name: Kotlin build

on:
  push:
    branches:
    - develop
  pull_request:
    branches:
    - develop

jobs: 
  build:
    runs-on: ubuntu-latest

    steps: 
      - uses : actions/checkout@v1


      - name: set up JDK
        uses: actions/setup-java@v1
        with: 
          java-version: 15.0.2


      - name: Emplacement of racine file
        run: ls -ali
      
      
      - name: Emplacement of racine file
        run: dir


      - name: Make gradlew executable
        run: chmod +x ./epicture_project/gradlew

      - name: Build debug apk
        run: ./epicture_project/gradlew clean assembleDebug

      - name: Create release and upload apk
        uses: underwindfall/create-release-with-debugapk@v2.0.0
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v1.0.0
          asset_path: app/build/outputs/apk/debug/app-debug.apk
          asset_name: Epicture.apk
          asset_content_type: application/zip